version: '3.4'

x-common-variables: &common-variables
  MYSQL_ROOT_PASSWORD: p@ssw0rd
  MYSQL_DATABASE: tokendb
  MYSQL_PORT: 3306
  MYSQL_USER: txnuser
  MYSQL_PASSWORD: p@ssword

services:
  backend:
    build: .
    ports:
     - "5001:5000"
    depends_on:
     - db
    environment:
      <<: *common-variables
      #DB_HOST: "docker.for.mac.localhost"

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
#      - ./sql/init.sql:/data/application/init.sql
    restart: always
    ports:
      - "33306:3306"
    environment:
      <<: *common-variables

volumes:
  db_data: {}
